### PR TITLE
add Cargo.lock

### PR DESCRIPTION
**Pull request by imlonghao**
https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

> If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or cdylib, check Cargo.lock into git

https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

### CODE REVIEW

**Review by oluceps — APPROVED** [review]
It could provide deterministic build environment and process, which are critical for linux distribution software repository packaging works and using by terminal users.

**Comment by EAimTY** [comment]
The project structure is changed in the new version. We got 2 libraries and 2 binaries in one cargo workspace. I'm not sure if we have any way to omit the lock file of the libraries but retain binaries' one.

**Comment by oluceps** [comment]
> The project structure is changed in the new version. We got 2 libraries and 2 binaries in one cargo workspace. I'm not sure if we have any way to omit the lock file of the libraries but retain binaries' one.

In general, all crates in a Rust Workspace should use the same Cargo.lock file to lock their dependencies' versions. I don't understand the reason for omitting the lock file of the libraries.

The lack of a lock file did make some trouble while packaging for distros.

**Comment by EAimTY** [comment]
> > The project structure is changed in the new version. We got 2 libraries and 2 binaries in one cargo workspace. I'm not sure if we have any way to omit the lock file of the libraries but retain binaries' one.
> 
> In general, all crates in a Rust Workspace should use the same Cargo.lock file to lock their dependencies' versions. I don't understand the reason for omitting the lock file of the libraries.
> 
> The lack of a lock file did make some trouble while packaging for distros.
> 
> And here ref to [Cargo book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#:~:text=If%20you%E2%80%99re%20building%20an%20end%20product%2C%20which%20are%20executable%20like%20command%2Dline%20tool%20or%20an%20application%2C%20or%20a%20system%20library%20with%20crate%2Dtype%20of%20staticlib%20or%20cdylib%2C%20check%20Cargo.lock%20into%20git)

Sounds good to me. Anyone wanna resolve the conflict / open a new PR?

**Pull request closed without merging**
